services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - ENV=development
      - SECRET_KEY=qwerty
      - HOST=localhost
      - PORT=8000
    env_file: 
      - ./server/.env 

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:8000/api/v1
    env_file:
      - ./client/.env